### ISSUE TITLE
NCP and LTC mixture

### ISSUE THREAD

**Issue by manyfeatures** [mlech26l/keras-ncp#19]
If I understand correctly this repo is bound to LTC and NCP papers at the same time.
But LTC in the paper is described in general case without `wirings` class that is used in NCP.
In this repo the LTC cell is strongly based on the NCP architucture.
Can the different neural network be used in the LTC cell using code from repo?

**Comment by mlech26l** [comment]
Yes, NCP is the LTC neural model combined with wirings.

If you want to use the plain LTC cell, use the FullyConnected wiring:

```python
num_units = 64
wiring = kncp.wirings.FullyConnected(num_units)
ltc_cell = LTCCell(wiring)
```

Note that there is a minor overhead because of the support of non-fully connected wirings, however, this should matter that much. 
Also, the parameterization (choice and name of the parameters) is done according to the NCP paper and might be a bit different than in the LTC one.
