### ISSUE TITLE
GPU performance issues

### ISSUE THREAD

**Issue by PereUbu7** [mlech26l/keras-ncp#24]
Hi!
Thanks for great work!

I've got this model:

ncp_wiring = kncp.wirings.NCP(
    inter_neurons=40, 
    command_neurons=14,  
    motor_neurons=2*6,  
    sensory_fanout=20, 
    inter_fanout=10,  
    recurrent_command_synapses=10,  
    motor_fanin=10, 
)
ltc_cell = LTCCell(ncp_wiring)

model = tf.keras.Sequential()
model.add(tf.keras.layers.InputLayer(input_shape=(300, 16)))
model.add(tf.keras.layers.RNN(ltc_cell, return_sequences=False))
model.add(tf.keras.layers.Reshape([6, 2]))

At inference on a machine with tf 2.3.0 (no GPU) and 4 cores, 14 GB RAM I get an inference time of about 0.11s.
Same tf version with GPU support but on a machine with a 4 x NVIDIA Tesla K80 and 24 cores, 224 GB RAM my inference time lies at about 0.64s

No specific warnings from tf about GPU incompatibilities to model.

Do your models perform well with GPUs?

**Comment by mlech26l** [comment]
Hi,

I would expect these numbers.

The processing of long time series, such as 300 timesteps as in your case, combined with low-dimensional inputs/RNN size, usually runs faster on CPU than GPU. (especially when also using a small batch size).

This is because the 300 timesteps need to be processed sequentially, whereas GPU favors parallel workloads.

**Comment by PereUbu7** [comment]
Hi,

OK. Thank you for your answer!
